package com.quxin.freshfun.dao;

import java.util.List;
import java.util.Map;

import com.quxin.freshfun.model.goods.GoodsTypePOJO;

public interface GoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int insert(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int insertSelective(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    GoodsTypePOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsTypePOJO record);
    /**
     * 
     * @param goodsType
     * @return
     */
    public int addGoodsType(GoodsTypePOJO goodsType);
    /**
     * 
     * @param goodsType
     * @return
     */
    public boolean updateGoodsType(GoodsTypePOJO goodsType);
    /**
     * 
     * @param id
     * @return
     */
    public GoodsTypePOJO findById(int id);    
    /**
     * 
     * @return
     */
    public List<GoodsTypePOJO> findAll();
    /**
     * 
     * @param isDeleted
     * @return
     */
    public boolean deleteGoodsType(int id);
    
    
    public List<GoodsTypePOJO> findByPage(Map<String,Object> map);
    
    
    
    
    
}